fix blue/green

diff --git a/.github/workflows/docker-compose.yml b/.github/workflows/docker-compose.yml
--- a/.github/workflows/docker-compose.yml
+++ b/.github/workflows/docker-compose.yml
@@ -53,14 +53,20 @@ jobs:
     - name: SSH and Deploy
       run: |
         ssh -o StrictHostKeyChecking=no root@49.12.15.46 << 'ENDSSH'
-        cd /var/www/cms
         docker login ghcr.io -u degun -p ${{ secrets.TOKEN }}
         docker pull ghcr.io/degun/pages-cms:latest
+        docker rm -f cms_new || true
         docker run -d --name cms_new --restart unless-stopped -p 1989:1988 ghcr.io/degun/pages-cms:latest
-        sleep 5
-        curl -f http://localhost:1989 || (echo "Health check failed"; docker stop cms_new && docker rm cms_new && exit 1)
-        docker stop cms && docker rm cms
+        sleep 10
+        if ! curl -f http://localhost:1989; then
+          echo "New container failed health check, aborting deployment."
+          docker rm -f cms_new
+          exit 1
+        fi
+        docker rm -f cms || true
         docker rename cms_new cms
+        docker stop cms
         docker run -d --name cms --restart unless-stopped -p 1988:1988 ghcr.io/degun/pages-cms:latest
         ENDSSH
-     
+    
+  
